<?php

namespace Mbsoft31\MbsoftBlog;

use Mbsoft31\MbsoftBlog\Contracts\DatabaseDriverContract;
use Mbsoft31\MbsoftBlog\Drivers\DatabaseDriver;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Mbsoft31\MbsoftBlog\Commands\MbsoftBlogCommand;

class MbsoftBlogServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('mbsoft-blog')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigration('create_mbsoft-blog_table')
            ->hasCommand(MbsoftBlogCommand::class);
    }

    public function boot()
    {
        $this->app->singleton(DatabaseDriverContract::class, DatabaseDriver::class);
        $this->app->singleton('mbsoft-blog', MbsoftBlog::class);
        return parent::boot(); // TODO: Change the autogenerated stub
    }
}
